### ISSUE TITLE
Level 13 --> (1-)

### ISSUE THREAD

**Issue by AaymanS** [MotherTeresaHS/ICS2OSpring2018FinalProject#146]
All of these now work, can someone check if:
i) Wall to not fall off the edge
ii) Appropriate blobs
iii) Appropriate size (much bigger than Lv 0)
iv) Appropriate coins and coins sound like slimes
v) The door at the end works

**Comment by kangminkim123** [comment]
it is work.

**Comment by Mr-Coxall** [comment]
OK
