### ISSUE TITLE
level 2

### ISSUE THREAD

**Issue by TheBellemTower** [MotherTeresaHS/ICS2OSpring2018FinalProject#16]
-make a map
-create a character
-create enemies
-create  blobs
-create exit
-create coins
-create spikes
-create water
-spikes damage you
-blobs damage you- floating ice gives you points
-water kills you if you fall in it
- forest(exit) at the end lets you escape
-enemies hurt you

**Comment by CitrusMelon** [comment]
All is good and working. Well done

**Comment by Mr-Coxall** [comment]
OK
