### ISSUE TITLE
Level 13 --> (1)

### ISSUE THREAD

**Issue by AaymanS** [MotherTeresaHS/ICS2OSpring2018FinalProject#167]
Can someone see if:

i) The door sounds like a thud?

**Comment by kangminkim123** [comment]
it is working

**Comment by AaymanS** [comment]
Can someone see if the background noise is windy?

**Comment by ryanlalonde1** [comment]
background is windy

**Comment by kangminkim123** [comment]
working

**Comment by AaymanS** [comment]
Can someone see if the sword gives you 1000 and sounds different from the choco coins?

**Comment by Mr-Coxall** [comment]
OK

Level 1
