### ISSUE TITLE
Level 1 (1-)

### ISSUE THREAD

**Issue by CitrusMelon** [MotherTeresaHS/ICS2OSpring2018FinalProject#17]
Need to create tiled map:

- Wall so the hero can't fall backwards off the map
- Blobs shown
- Enemies shown
- Coins that give points when touched
- Blobs that damage hero when touched 
- Spikes that damage hero when touched 
- Enemies that damage hero when touched 
- Blobs that are killed when the hero jumps on them 
- Enemies that are killed when the hero jumps on them 
- Door to return to menu

**Comment by GillianGonzales** [comment]
All of these objectives of checked, and all objectives work good job

**Comment by Mr-Coxall** [comment]
Level complete
