### ISSUE TITLE
Change level 11 sound effects and added a new coin

### ISSUE THREAD

**Issue by KrisAsante** [MotherTeresaHS/ICS2OSpring2018FinalProject#177]
- New thud sound
- New sword sound
- New squish sound
- New slime sound
- New door sound
- New hurt 1 and 2 sound
- New hit sound
- New coin sound
- Added a new coin object called Golden Diamond which adds the value "999" to score when collected

Sound Sources:
Sword: https://www.youtube.com/watch?v=U34MegCHlig
Hurt1 & 2: https://www.youtube.com/watch?v=pOH3pKTqHr0 around 0:20
Door: https://www.youtube.com/watch?v=Uqb79AaQ2tY
Hit: https://www.youtube.com/watch?v=fa-XmBMtn54
Slime: https://www.youtube.com/watch?v=XxbTFBkNfgQ
Squish: https://www.youtube.com/watch?v=Hr46imSXZv8
Thud: https://www.youtube.com/watch?v=zaYFyDTgGjY
Coin: https://www.youtube.com/watch?v=uAId03oeuFY

**Comment by Mouaffakkub** [comment]
Everything written down works

**Comment by Mr-Coxall** [comment]
OK

Level 1+
