### ISSUE TITLE
FIRST ISSUE

### ISSUE THREAD

**Issue by Mouaffakkub** [MotherTeresaHS/ICS2OSpring2018FinalProject#19]
1-Create map
2-Get character to show up on the screen
3-Create enemies and blobs
4-Create exit
5-Can only see map
6-Have an invisible wall to not fall off the edge
7-Is an appropriate size
9-Has coins

**Comment by ryanlalonde1** [comment]
its all good

**Comment by mominahmed99** [comment]
it is working

**Comment by Mr-Coxall** [comment]
OK.

This s for Level -1
