### ISSUE TITLE
Level9 issue for a level 1+

### ISSUE THREAD

**Issue by Mouaffakkub** [MotherTeresaHS/ICS2OSpring2018FinalProject#193]
1- Create new background space music
2- create new sound effect when collecting a coin
3- Create new coin object worth more

**Comment by KrisAsante** [comment]
Everything typed on this issue works fine no bus at all, Good Job

**Comment by fawazmez** [comment]
it works

**Comment by Mr-Coxall** [comment]
OK

Level 1+
