### ISSUE TITLE
10

### ISSUE THREAD

**Issue by ryanlalonde1** [MotherTeresaHS/ICS2OSpring2018FinalProject#21]
create a map
create a hero
create a enemy
create a blob
create coins

**Comment by Mouaffakkub** [comment]
Everything is working just fine

**Comment by mominahmed99** [comment]
everything is working properly

**Comment by Mr-Coxall** [comment]
Must be re-checked.
I walked off the edge of the world.

**Comment by Mr-Coxall** [comment]
OK.
Level 1-
