### ISSUE TITLE
Level 10 changing sound effects and added new coins

### ISSUE THREAD

**Issue by ryanlalonde1** [MotherTeresaHS/ICS2OSpring2018FinalProject#228]
. coin3 = 1000
. coin4 = 600
added new sound
death
squish
background music 
coins

**Comment by Mouaffakkub** [comment]
No bugs and working

**Comment by KrisAsante** [comment]
Everything written down is working perfectly. The coins added give the values written down on the issue.
Good Job

**Comment by Mr-Coxall** [comment]
OK

Level 1+
