### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by Mouaffakkub** [MotherTeresaHS/ICS2OSpring2018FinalProject#239]
create background music: https://www.youtube.com/watch?v=jHcWhQUmJ8E&index=7&list=PLobY7vO0pgVKn4FRDgwXk5FUSiGS8_jA8

**Comment by fawazmez** [comment]
good

**Comment by Adamguettit** [comment]
works

**Comment by Mr-Coxall** [comment]
OK

Level 2-
