### ISSUE TITLE
level 5

### ISSUE THREAD

**Issue by fawazmez** [MotherTeresaHS/ICS2OSpring2018FinalProject#26]
i will be making the level 5
test cases:
.Wall so the hero can't fall backwards off the map
.Blobs shown
.Enemies shown
.Coins that give points when touched
.Blobs that damage hero when touched
.Spikes that damage hero when touched
.Enemies that damage hero when touched
.Blobs that are killed when the hero jumps on them
.Enemies that are killed when the hero jumps on them
.Door to return to menu
.Enemies that run after the player

**Comment by Adamguettit** [comment]
it works

**Comment by fawazmez** [comment]
it works

**Comment by Mr-Coxall** [comment]
OK for Level -1.
