### ISSUE TITLE
Does Level 14 work

### ISSUE THREAD

**Issue by GillianGonzales** [MotherTeresaHS/ICS2OSpring2018FinalProject#28]
1- -> have a functional scene
can only see map; no blank spots
have wall to not fall off the edge
have appropriate built in blobs and enemies
is an appropriate size (can not be the same dimension as mine, but must be at least the same area)
has appropriate coins
has a door (or portal) to get back to level menu

**Comment by TheBellemTower** [comment]
yes it works good job
