### ISSUE TITLE
add level 6

### ISSUE THREAD

**Issue by wendiyu** [MotherTeresaHS/ICS2OSpring2018FinalProject#29]
Create level 6 map
Make level 6 show up in corona.
Blobs shown
Enemies shown
Coins that give points when touched
Spikes that damage hero when touched
Enemies that damage hero when touched
Blobs that are killed when the hero jumps on them
Enemies that are killed when the hero jumps on them
Door to return to menu

**Comment by SebastianN8** [comment]
It shows up, blobs are there, enemies too, coins give points, spikes harm, enemy harms too, blops are killed, the door works. This level does everything it is supposed to do.

**Comment by Mr-Coxall** [comment]
OK

Level 1
